### ISSUE TITLE
Finding DSM tiles via the API

### ISSUE THREAD

**Issue by smr547** [GeoscienceAustralia/agdc#12]
It's not obvious how to obtain a DSM tile via the API and there are no examples.

```python
   tiles=list_tiles_wkt(wkt,satellites=[Satellite.LS7], years=[2005, 2006, 2007], \
     datasets=[DatasetType.ARG25, DatasetType.PQ25, DatasetType.FC25, DatasetType.DSM], \
     database=config.get_db_database(), user=config.get_db_username(), \
     password=config.get_db_password(), \
     host=config.get_db_host(), port=config.get_db_port())
```
doesn't work.

**Comment by simonoldfield** [comment]
The DSM/DEM tiles were not included in the initial query API prototype as they have a slightly different structure (no satellite, fuzzy definition of acquisition date, etc) and it seemed likely the DB structure was going to change anyway.  Also none of the applications on my list actually needed them initially either.

I've just started adding them in so you should be able to retrieve them "imminently".

**Comment by smr547** [comment]
Excellent!

On Mon, Feb 2, 2015 at 10:20 AM, Simon Oldfield <notifications@github.com>
wrote:

> The DSM/DEM tiles were not included in the initial query API prototype as
> they have a slightly different structure (no satellite, fuzzy definition of
> acquisition date, etc) and it seemed likely the DB structure was going to
> change anyway. Also none of the applications on my list actually needed
> them initially either.
>
> I've just started adding them in so you should be able to retrieve them
> "imminently".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoscienceAustralia/agdc/issues/12#issuecomment-72390795>
> .
>



-- 
*Steven Ring*
Software Engineer
BSc MIT (ANU)
m: 0417 495 268
f: +61 2 6100 9273
s: stevering

**Comment by simonoldfield** [comment]
I just pushed a change to allow DTM (DSM, DEM, DEM[H], DEM[S]) tiles to be retrieved.  I initially added them into the `list_tiles` methods but then thought better of it as they don't fit the model of having acquisition and satellite info.

So there is a new (and potentially soon to be obsoleted once I get to the whole refactoring stuff :smile:) method `list_tiles_dtm`.

An example usage is...

```
    tiles = list_tiles_dtm(x=[123], y=[-25],
                           datasets=[DatasetType.DSM, DatasetType.DEM, DatasetType.DEM_HYDROLOGICALLY_ENFORCED,
                                     DatasetType.DEM_SMOOTHED],
                           database=config.get_db_database(), user=config.get_db_username(),
                           password=config.get_db_password(),
                           host=config.get_db_host(), port=config.get_db_port())

    for tile in tiles:
        _log.info("Found tile xy = %s acq date = [%s] DSM= [%s]", tile.xy, tile.end_datetime, tile.datasets[DatasetType.DSM].path)
```
which will do something like...
```
INFO:root:Found tile xy = (123, -25) acq date = [None] DSM = [/g/data1/rq6/DSM/EPSG4326_1deg_0.00025pixel/dsm1sv1_0_Clean.img/DSM_123_-025.tif]
```

**Comment by smr547** [comment]
Many thanks Simon. This will allow WOfS' refactor to go ahead with the API.  

If an API refactor does occur, it would be really nice to get the DSM dataset back from the API as a part of the collection of datasets that have been requested by the application. This is a nice feature of the API and minimises the amount of work the app has to do to collect data ready for processing.

**Comment by simonoldfield** [comment]
:laughing: that was actually the first thing I did and then I changed my mind and implemented the just return DTM tiles (as they have no satellite and acquisition information like the others).

I'll re-instate the DTM tiles into the standard `list_tiles` method so for each cell/acquisition you will get back a list of datasets - NBAR, PQA, FC, (WOFS), DSM, DEM, ....

**Comment by smr547** [comment]
Even better :-)
Thank you

**Comment by simonoldfield** [comment]
The `list_cells` and `list_tiles` functions from the `datacube.api.query` module support `DSM`, `DEM`, `DEM_HYDROLOGICALLY_ENFORCED` and `DEM_SMOOTHED` dataset types.

Refer to the [API Python Function Reference](http://geoscienceaustralia.github.io/agdc/api/0.1.0/html/api/datacube.api.query.html).

An example is...
```
>>> from datacube.api.query import list_cells, list_tiles
>>> from datacube.api.model import Satellite, DatasetType
>>> from datetime import datetime

>>> for cell in list_cells(x=[120], y=[-20], satellites=[Satellite.LS5, Satellite.LS7], acq_min=datetime(2014,12,1), acq_max=datetime(2014,12,31), dataset_types=[DatasetType.ARG25, DatasetType.DEM]):
...     print cell.xy
...
(120, -20)
```

or to list the datasets...

```
>>> from datacube.api.query import list_cells, list_tiles
>>> from datacube.api.model import Satellite, DatasetType
>>> from datetime import datetime

>>> for tile in list_tiles(x=[120], y=[-20], satellites=[Satellite.LS5, Satellite.LS7], acq_min=datetime(2014,12,1), acq_max=datetime(2014,12,31), dataset_types=[DatasetType.ARG25, DatasetType.DEM]):
...     print tile.datasets[DatasetType.DEM].path
...
/g/data1/rr1/agdc_elevation_tiles/EPSG4326_1deg_0.00025pixel/DEM/1secSRTM_DEMs_v1.0-DEM.vrt/DEM_120_-020.tif
/g/data1/rr1/agdc_elevation_tiles/EPSG4326_1deg_0.00025pixel/DEM/1secSRTM_DEMs_v1.0-DEM.vrt/DEM_120_-020.tif
```
