### ISSUE TITLE
Distributed database for the AGDC

### ISSUE THREAD

**Issue by smr547** [GeoscienceAustralia/agdc#14]
This suggestion is motivate by our experience using the Datacube RDBMS on HPC (Raijin in this case, for the WOfS application). 

Typical HPC jobs involve parallel execution or many (perhaps thousands) of independent UNIX tasks. Each task often acts as a database client. In this architecture, the central database is a potential bottleneck. If the database becomes overload, it impacts the job in question and all other AGDC users. Throughput falls off and if the database needs rebooting, large jobs can be lost.

The use of a distributed database is worth considering?

Between ingestion runs, the AGDC database remains in a static, read only state. The HPC analysis runs do not update the database.

So here's the suggestion.

a) We "publish" a new version of the AGDC database each time we do an ingestion. The database is "published" as a single DB content file.

b) When a HPC job starts it is allocated a cluster of one or more nodes. Each node has 16 CPUs and a 400GB solid state disk (SSD). When a Datacube analysis job starts, the first step is to copy the database content file to the SSD. A single lightweight DB server can then be started on the node. Each unix task running on the node communicates only with it's local DB server. Alternatively each UNIX task could use a lightweight imbedded SQL server to access the same DB content on the SSD (SQLite comes to mind). All DB operations are performed "on-node". At the end of the HPC run, the DB on the SSD is discarded.

c) The current central DB server is maintained to service the non-HPC clients.

Advantages
----------------
- No central database server to bottleneck
- Little or no change to existing API code (we still use SQL)
- The AGDC RDBMS becomes naturally "versioned" with each ingestion run creating a new version (hey, this sounds like a big win for provenance tracking and good data governance)
- Speed improvement during task execution -- SSD I/O is very very FAST!!!
- memory savings and simplified API design (We can use generators to iterate over a SQL result sets without fear of destroying the central server)

Disadvantage
------------------
- Extra step during PBS job setup (one or two lines of BASH)
- Additional I/O and runtime during DB->SSD copy (but Lustre is FAST and is designed for this type of copy operation)
- Consumption of SSD (but our databases are not big, and we don't typically use the SSD anyway)

Thinking ahead a little to when databases are larger, we could further partition our databases along the lines of "Landsat DB", "Modis DB" in addition to "Everything DB". The DB could also be partitioned by year.  Or dynamically partitioned at the beginning of a HPC run before being distributed to the nodes .... a kind of AGDC-Map-Reduce pattern.

But I'm getting ahead of myself.

How do you feel about distributing our AGDC DB to the nodes?

cheers
Steven

**Comment by simonoldfield** [comment]
Database scalability has been (briefly) discussed previously.  The short-answer is that it is intended to be dealt with when it becomes an issue and there are lots of fairly simple approaches to this.

I've suggested (in vague, ill-defined and not even half thought through ways) that for smaller scale analysis we could actually have local (e.g. not at the NCI) database instances and the API could transparently retrieve the datasets from the NCI to allow them to be processed without the end-user needing to know too much about it.

My thinking was that CSIRO's "managed subset" (or mini-cube) could be implemented this way.

Something like that anyway.

**Comment by smr547** [comment]
The latter two ideas do not directly address scalability on the HPC
platform. They suggest ways of moving small sections of processing load
elsewhere.

I agree that we do not currently have a scalability problem and we can
defer the issue, whilst continuing to discuss the options. A central
database will always be a bottleneck in a HPC environment and, if the
datacube attracts more users, we will have to deal with it.



On Fri, Jan 30, 2015 at 11:20 AM, Simon Oldfield <notifications@github.com>
wrote:

> Database scalability has been (briefly) discussed previously. The
> short-answer is that it is intended to be dealt with when it becomes an
> issue and there are lots of fairly simple approaches to this.
>
> I've suggested (in vague, ill-defined and not even half thought through
> ways) that for smaller scale analysis we could actually have local (e.g.
> not at the NCI) database instances and the API could transparently retrieve
> the datasets from the NCI to allow them to be processed without the
> end-user needing to know too much about it.
>
> My thinking was that CSIRO's "managed subset" (or mini-cube) could be
> implemented this way.
>
> Something like that anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoscienceAustralia/agdc/issues/14#issuecomment-72131780>
> .
>



-- 
*Steven Ring*
Software Engineer
BSc MIT (ANU)
m: 0417 495 268
f: +61 2 6100 9273
s: stevering

**Comment by simonoldfield** [comment]
We have always talked about having the ability to replace the single database instance with, for example, a database cluster.  The scalability of the database is not expected to be an issue in the foreseeable future and there are many and varied well known solutions to this.

I'm closing this for now so that it doesn't become a distraction from the immediate tasks at hand.
