### ISSUE TITLE
Optional sort sequences for Tiles  

### ISSUE THREAD

**Issue by smr547** [GeoscienceAustralia/agdc#16]
The query API currently returns tiles sorted by end_date. Some apps may want to sort by satellite, others may want to sort by lat/long (cell_id). I'm wondering if a "sort_key" parameter on ``list_tiles_as_generator`` and ``list_tiles_as_list`` methods would be useful?  Such a parameter would allow the DB to do the sorting and avoid in-memory sorting of Python objects. Of course, this is only an issue for large tile sets.

Not a firm suggestion at this stage, just a question.

**Comment by simonoldfield** [comment]
The `list_cells` and `list_tiles` functions of the `datacube.api.query` module have supported a `sort` parameter (`SortType.ASC` or `SortType.DESC`) for quite a while.

See the [API Python Function Reference](http://geoscienceaustralia.github.io/agdc/api/0.1.0/html/api/datacube.api.query.html).

For `list_cells` the sort is on `x` and then `y` with the sort order applied to both.

For `list_tiles` the sort is on `x`, `y`, `acquisition_date` and then `satellite` with the sort order applied to the `acquisition_date` (all others are sorted ascending).
