### ISSUE TITLE
Implement Retrieve Pixel Time Series tool

### ISSUE THREAD

**Issue by simonoldfield** [GeoscienceAustralia/agdc#27]
Implement a tool to retrieve a time series of values for an individual pixel from an arbitrary data set.

**Comment by simonoldfield** [comment]
Refer to the [API Command Line Tools](http://geoscienceaustralia.github.io/agdc/api/0.1.0/html/api_tools.html)

**Comment by llymburn** [comment]
The instance of `retrieve_pixel_time_series.py`  implemented in 0.1.0-b20150427 (aka 0.1.0 2015-04-27 snapshot) puts the coastal aerosol blue band into the last column of the CSV, it needs to be in the first column so that the spectra contained in the text file are wavelength sequential
