### ISSUE TITLE
Allow Retrieve Dataset Stack tool to operate over satellites with non-identical bands

### ISSUE THREAD

**Issue by simonoldfield** [GeoscienceAustralia/agdc#40]
For example over LS5, LS7 and LS8 for NBAR.
The options that immediately spring to mind for dealing with this are:
1. only output the common bands
2. output the superset of bands with no value for datasets that don't have the band

**Comment by gamedaygeorge** [comment]
Not sure of the full context, but my first reaction would be (2), with a null value for missing bands. There is also a question in my head about the definition of 'common'. Does that mean precise overlap? Partial overlap? For LS might be relatively clear, but if you add an arbitrary band definition in there, do things get complicated?

**Comment by simonoldfield** [comment]
Implemented in 0.1.0-b20150430 (aka 0.1.0 2015-04-30 snapshot).

The _Retrieve Dataset Stack_ tool now supports the ``--bands-all`` and ``--bands-common`` command line arguments.

With the ``--bands-all`` argument a stack is created for all possible bands.

With the ``--bands-common`` argument a stack is created only for bands common to all datasets.

The default behaviour is ``--bands-all``.
