### ISSUE TITLE
flyway configuration example - minor change suggested

### ISSUE THREAD

**Issue by simonaoliver** [GeoscienceAustralia/agdc#74]
Suggested for ease of install - add the following to the flyway example configuration:

- Change user to cube_admin
- Change password to cube_admin
- Add flyway.schemas=datacube
- the flyway locations also implies an installation location for flyway - maybe replace with <agdc root install>/database/sql

**Comment by jeremyh** [comment]
- Renamed agdc-default.conf to agdc-example.conf, which more accurately reflects it's role.
- Changed default user to cube_admin, and added comments to clarify when to use admin vs user.
- Made default schemas consistent between Flyway conf and datacube.conf

Setting the flyway location to '/database/sql' would imply an even stronger forced locationo, wouldn't it? Not to mention forced OS. Currently it's a relative path, so if you unzip Flyway into the database folder, and name it `flyway`, it should "just work".
