### ISSUE TITLE
Wrong agdc-example.conf content

### ISSUE THREAD

**Issue by didierearith** [GeoscienceAustralia/agdc#81]
Hi AGDC Team,

Since some agdc configuration file sections and keys have changed, the agdc-example.conf file no longer suits.

I think it should be:
[DATABASE]
...
database = datacube
username = cube_admin
password = cube_admin
...

**Comment by simonoldfield** [comment]
The agdc-example.conf file is part of the "non-API" codebase and is used by thing like the stacker and ingester.  The question of how we handle an AGDC "config" is going to come back to the decisions around how we package all the different components (ingest, API, etc) - i.e. are they one thing or multiple independent things.

**Comment by simonoldfield** [comment]
The config information (for the API) has been moved out of the code.
    
    The API will now look for a configuration file in the following places in the following order:
      1.  $AGDC_API_CONFIG
      2.  $HOME/.datacube/config

This should contain something like:
```
[DATABASE]
host: <hostname or ip address>
port: <5432 or 6432>
database: <datacube>
username: <cube_user>
password: <cube_user>
schemas: agdc, public, gis, topology
```

**Comment by simonoldfield** [comment]
Merged into develop - now requires either a config file pointed at by `$AGDC_API_CONFIG` or `$HOME/.datacube/config`.
